// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:receipt_management_flutter/core/enums/receipt_status.dart';
import 'package:receipt_management_flutter/core/enums/sync_operation.dart';
import 'package:receipt_management_flutter/core/enums/sync_status.dart';
import 'package:receipt_management_flutter/core/enums/template_type.dart';
import 'package:receipt_management_flutter/data/models/business_profile_model.dart';
import 'package:receipt_management_flutter/data/models/customer_model.dart';
import 'package:receipt_management_flutter/data/models/receipt_item_model.dart';
import 'package:receipt_management_flutter/data/models/receipt_model.dart';
import 'package:receipt_management_flutter/data/models/sync_queue_model.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(BusinessProfileModelAdapter());
    registerAdapter(CustomerModelAdapter());
    registerAdapter(ReceiptItemModelAdapter());
    registerAdapter(ReceiptModelAdapter());
    registerAdapter(ReceiptStatusAdapter());
    registerAdapter(SyncOperationAdapter());
    registerAdapter(SyncQueueModelAdapter());
    registerAdapter(SyncStatusAdapter());
    registerAdapter(TemplateTypeAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(BusinessProfileModelAdapter());
    registerAdapter(CustomerModelAdapter());
    registerAdapter(ReceiptItemModelAdapter());
    registerAdapter(ReceiptModelAdapter());
    registerAdapter(ReceiptStatusAdapter());
    registerAdapter(SyncOperationAdapter());
    registerAdapter(SyncQueueModelAdapter());
    registerAdapter(SyncStatusAdapter());
    registerAdapter(TemplateTypeAdapter());
  }
}
